# Generated by Django 3.2.3 on 2021-05-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Enter the brand name of the item.', max_length=25)),
                ('product', models.CharField(help_text='Enter the item description.', max_length=75)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
