# Generated by Django 3.2.3 on 2021-05-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_supplies_plus_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='product',
            field=models.CharField(help_text='Enter the item description.', max_length=75, unique=True),
        ),
    ]
