# Generated by Django 3.2.3 on 2021-06-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_supplies_plus_inventory', '0003_stockitem_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='category',
            field=models.CharField(default='general', max_length=25),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product',
            field=models.CharField(help_text='Enter the item description.', max_length=75),
        ),
    ]
